### ISSUE TITLE
AADSTS500011: Unable to acquire token in the console application

### ISSUE THREAD

**Issue by Arash-Sabet** [Azure-Samples/active-directory-dotnetcore-daemon-v2#105]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Simply follow all configuration steps on both AD and the daemon application.

### Any log messages given by the failure
> AADSTS500011: The resource principal named api://abcdef-555-1111-2222-6666666 was not found in the tenant named {tenant name}. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.

### Expected/desired behavior
>
This issue should not happen
### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@Arash-Sabet 
I'm assuming you went through the following chapter: [2-Call-OwnApi](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/2-Call-OwnApi)

Could you please check the App ID URI of your web api?

**Comment by Arash-Sabet** [comment]
I am pretty much sure that I went through the steps right. There's a similar daemon app that I was able to get the token successfully but this one fails. Should ./default thing be declared somewhere as a scope on AD?

**Comment by jmprieur** [comment]
No: .default means all what was pre-authorized (all what the admin has pre-consented to). You'd only want to expose app permissions. See https://docs.microsoft.com/azure/active-directory/develop/scenario-protected-web-api-app-registration#if-your-web-api-is-called-by-a-daemon-app.

In https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/2-Call-OwnApi#register-the-client-app-daemon-console, did you do step 6? (admin consent)

**Comment by Arash-Sabet** [comment]
Would you be able to review and approve the PR associated with this issue?

**Comment by jmprieur** [comment]
Thanks @Arash-Sabet : I've suggested a change: https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/pull/106

cc; @kalyankrishna1

**Comment by Arash-Sabet** [comment]
@jmprieur I left a couple of notes on the PR #106 and hope you can address them. I was able to obtain the token and send it to the Web API but the API refused to authorize the request. So the token validation failed. Not sure if there are some specifics in the Web API configuration documentation needs to be amended too. That's what I could not figure out despite everything in the both applications' appsettings.json files look good. Any advice on that considering the points we discovered on PR #106 ?

**Comment by Arash-Sabet** [comment]
Closing this issue as PR #106 merged the changes.
