### ISSUE TITLE
Sample should mention that the CCA object is singleton or to customize cache.

### ISSUE THREAD

**Issue by bgavrilMS** [Azure-Samples/active-directory-dotnetcore-daemon-v2#110]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

**Comment by v-michaelmi** [comment]
@bgavrilMS 

Do you mean this of as more of a README or code change?

I have a PR up that access the `ConfidentialClientApplication` through a service referenced [here](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/blob/d95b24eb30a81a5d5ae2661aafab6760b23c004f/2-Call-OwnApi/daemon-console/Services/ConfidentialClientApplicationService.cs).

You can see it being used in another service making HTTP calls in the `PrepareHttpClientAsync` method of the `TodoService` [here](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/blob/d95b24eb30a81a5d5ae2661aafab6760b23c004f/2-Call-OwnApi/daemon-console/Services/TodoService.cs).

**Comment by bgavrilMS** [comment]
It's fine, I see that caching is confgirued now: https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/blob/master/1-Call-MSGraph/daemon-console/Program.cs#L72
