### ISSUE TITLE
config.Authority does not exist in appsetting json

### ISSUE THREAD

**Issue by Infinitism** [Azure-Samples/active-directory-dotnetcore-daemon-v2#13]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Look at appsettings.json and the the program.cs file where it is using config.Authority from the config file which doesn't exist

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@Infinitism : I'm confused: the Authority is computed from the Instance and the Tenant. 
See https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/blob/22601938fe516be85e6c4ac095df49d36cdaa58c/daemon-console/AuthenticationConfig.cs#L59-L65
