### ISSUE TITLE
Error when running the sample

### ISSUE THREAD

**Issue by Sandjuro** [Azure-Samples/active-directory-dotnetcore-daemon-v2#134]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Add settings and run example

### Any log messages given by the failure
>'authority' Uri should have at least one segment in the path (i.e. https://<host>/<path>/...).

### Expected/desired behavior
>get a token

### OS and Version?
> Windows 10

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@[Sandjuro](https://github.com/Sandjuro):
which sub folder is it? did you read the README.md ?

**Comment by Sandjuro** [comment]
I solved the issue, it was an appsetting problem, I was adding the settings in a secure file and had one config name wrong.
