### ISSUE TITLE
Is the PoP without server nonce still not recommended?

### ISSUE THREAD

**Issue by bkwdesign** [Azure-Samples/active-directory-dotnetcore-daemon-v2#143]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
I just have a question about the README on the [daemon-console](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/2-basher/4-Call-OwnApi-Pop) `This sample corresponds to an implementation of PoP without server nonce that is no longer recommended`
### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
I am wondering if this [README](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/blob/2-basher/4-Call-OwnApi-Pop/README.md) which features this scary disclaimer  at the top still accurate? 

And if it is.. is it really bad for me to use this sample for my production scenario?
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by v-michaelmi** [comment]
Hey @bkwdesign 

Yes, as of now the warning on the README is still accurate and we do not recommend using that sample as it is currently.

Will keep this issue open for others to see as well.

**Comment by bgavrilMS** [comment]
Yes, but please note that we are working on a different POP protocol for confidential clients. POP + SHR is for public clients only as it is slower due to the nonce.
