### ISSUE TITLE
[Question] How/where to pass resource to avoid InvalidAuthenticationTokenAudience

### ISSUE THREAD

**Issue by arsamigullin** [Azure-Samples/active-directory-dotnetcore-daemon-v2#145]
> Please provide us with the following information:
>
Hello. Was able to successfully get auth token providing certificate. However, when using the token, I am getting InvalidAuthenticationTokenAudience error.
```
{
    "error": {
        "code": "InvalidAuthenticationTokenAudience",
        "message": "The access token has been obtained for wrong audience or resource 'api://<client_id>'. It should exactly match with one of the allowed audiences 'https://management.core.windows.net/','https://management.core.windows.net','https://management.azure.com/','https://management.azure.com'."
    }
}
```

The problem is when requesting auth token, the resource : "https://management.core.windows.net/" was not provided. Can you please where to pass the resource to generate the proper token?

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@arsamigullin : the scope to use should be "https://management.core.windows.net//.default"

**Comment by arsamigullin** [comment]
Thank you, this helped!
