### ISSUE TITLE
upgrade to v5, sample has apps.json with no explanation

### ISSUE THREAD

**Issue by OzBob** [Azure-Samples/active-directory-dotnetcore-daemon-v2#150]
1 could you please explain what the apps.json file is used for or generated from?
2 where has IGraphServiceUsersCollectionPage gone in v5?

```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

**Comment by jmprieur** [comment]
@OzBob : do you mean this file? https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/blob/master/1-Call-MSGraph/AppCreationScripts/apps.json ?

For MsGraph v5., @DarrellMiller?

**Comment by jmprieur** [comment]
@OzBob ?

**Comment by OzBob** [comment]
@jmprieur yep  https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/blob/master/1-Call-MSGraph/AppCreationScripts/apps.json
I was hoping that the sample would be upgraded to v5 and a schema and/or MSLearn article would describe what the rules were for intepreting the apps.json file (or it's replacement)
I understand IGraphServiceUsersCollectionPage has not been migrated, but some guidance on upgrading this sample that build upon: https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md would be useful for me.

**Comment by jmprieur** [comment]
this requires https://github.com/AzureAD/microsoft-identity-web/issues/2097, which is planned later.

**Comment by jmprieur** [comment]
Updated to Microsoft Graph SDK 5.0
