### ISSUE TITLE
What is PoP?

### ISSUE THREAD

**Issue by 3pillardeveloper** [Azure-Samples/active-directory-dotnetcore-daemon-v2#153]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

N/A

### Any log messages given by the failure
>

N/A

### Expected/desired behavior
>

Thorough documentation of what PoP is and stands for especially in the README.md file.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

N/A

### Versions
>

N/A

### Mention any other details that might be useful

N/A

**Comment by jennyf19** [comment]
details in the [MSAL.NET wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Proof-Of-Possession-(PoP)-tokens)

**Comment by jmprieur** [comment]
Fixed by https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/commit/7208eea6f74ae3607b1dd6737061928e0eef0334
