### ISSUE TITLE
Documentation needs to be updated after upgrade to Id.Web 2.5.0

### ISSUE THREAD

**Issue by buzzfrog** [Azure-Samples/active-directory-dotnetcore-daemon-v2#158]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
This documentation needs to be updated. It doesn't reflect the current status of the code:
https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/2-Call-OwnApi#about-the-code

**Comment by v-michaelmi** [comment]
Thanks for catching this.

Updating now.

**Comment by v-michaelmi** [comment]
Resolved with [b4188b](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/commit/b4188b72eaf9ea87967dbabac11d925fc12c3974).

Closing.
