### ISSUE TITLE
 Daemon-Console: No connection could be made because the target machine actively refused it!

### ISSUE THREAD

**Issue by mitnick2012** [Azure-Samples/active-directory-dotnetcore-daemon-v2#167]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
> :  No connection could be made because the target machine actively refused it. (localhost:44372)' on Daemon-Console\Program.cs  line : 28

### Expected/desired behavior
>

### OS and Version?
> Windows 11. 

### Versions
>  11 pro 64 bit

### Mention any other details that might be useful
I disabled firewall but even that the issue persist  and this is app.setting for console app : 

![apiissue](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/assets/2571909/3f753424-b680-4744-bcd2-f9a1351af7c1)

Thanks

**Comment by jmprieur** [comment]
@mitnick2012 
Assuming this is the chapter where the daemon calls your own web API?

Did you run both the web API and the daemon app?
https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/2-Call-OwnApi#step-4-run-the-sample

**Comment by mitnick2012** [comment]
Yes I run it now and I get 401 unauthorized message

**Comment by jmprieur** [comment]
Great. Now you want to enable logging in the web API and you'll see why.
See https://github.com/AzureAD/microsoft-identity-web/wiki/Logging

**Comment by mitnick2012** [comment]
good I added logging section on appsettings.json, and the following code on api startup class :
 services.AddLogging(configure => configure.AddConsole())
                 .Configure<LoggerFilterOptions>(options => options.MinLevel = Microsoft.Extensions.Logging.LogLevel.Debug);

but I can't find any logger file on my application bin path

**Comment by mitnick2012** [comment]
this is the detailed error Im facing :
Unhandled exception. System.Net.Http.HttpRequestException: 401 Unauthorized
   at Microsoft.Identity.Web.DownstreamApi.DeserializeOutput[TOutput](HttpResponseMessage response, DownstreamApiOptions effectiveOptions)
   at Microsoft.Identity.Web.DownstreamApi.GetForAppAsync[TOutput](String serviceName, Action`1 downstreamApiOptionsOverride, CancellationToken cancellationToken)

**Comment by mitnick2012** [comment]
please any one can help with this issue ?!

**Comment by abarberenaCPDS** [comment]
Hi @mitnick2012,

I found this issue today (yup, many months later), I was able to fix it updating the API Manifest

<img width="1183" alt="image" src="https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/assets/43246964/5b9f45b1-09fe-4179-82e2-91da1d10306e">

### Manifest Update

Set the `accessTokenAcceptedVersion` value from `null` to `2`

<img width="778" alt="image" src="https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/assets/43246964/888531a0-8a0d-443c-a164-a569bf9f8eeb">
