### ISSUE TITLE
2-Call-OwnApi instructions missing info about the Scope for TodoList-webapi-daemon-v2

### ISSUE THREAD

**Issue by zojovano** [Azure-Samples/active-directory-dotnetcore-daemon-v2#177]
Following section explains how to replace configuration values: https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/2-Call-OwnApi#configure-the-service-project
It specifies:

Open the TodoList-WebApi\appsettings.json file
Find the app key Domain and replace the existing value with your Azure AD tenant name.
Find the app key TenantId and replace the existing value with your Azure AD tenant ID.
Find the app key ClientId and replace the existing value with the application ID (clientId) of the TodoList-webapi-daemon-v2 application copied from the Azure portal.  

But the config also has Scopes key and document doesn't specify which value should be provided there:

{
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "TenantId": "[Enter here the tenantID or domain name for your Azure AD tenant]",
    "ClientId": "[Enter here the ClientId for your application]",
    "Scopes": "[Enter here the scopes for your web API]",
    "TokenDecryptionCredentials": [
    ]
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*"
}

Also, TokenDecryptionCredentials seems to be empty - is that correct?

**Comment by jmprieur** [comment]
Fixed.
The TokenDecryptionCredentials are empty as the web API wasn't configured to accept encrypted tokens
