### ISSUE TITLE
Using KeyVault sample missing in the repo

### ISSUE THREAD

**Issue by manupa-ms** [Azure-Samples/active-directory-dotnetcore-daemon-v2#180]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Solution file missing when navigated to https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/3-Using-KeyVault

### Any log messages given by the failure
> NA

### Expected/desired behavior
> Solution file be present as in #1, #2 and #4 sections

### OS and Version?
> Windows10. 

### Versions
> NA

> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
It's doc only
