### ISSUE TITLE
Id Web sample for calling a devops api with managed identity

### ISSUE THREAD

**Issue by JoshLozensky** [Azure-Samples/active-directory-dotnetcore-daemon-v2#185]
To promote usage of the new Managed Identity feature in Id Web, we need to create a new sample for it. Therefore, we will create a ch 5 sample for calling a Devops API using managed identity. We are choosing this scenario as it is not already covered by a specific Azure SDK.

**Comment by jmprieur** [comment]
Done. Samples 5 and 6
