### ISSUE TITLE
API calls to many methods

### ISSUE THREAD

**Issue by sam-wheat** [Azure-Samples/active-directory-dotnetcore-daemon-v2#197]
I have implemented [this sample](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/2-Call-OwnApi).

I need to make calls to many different methods on my api.  Since the method I cam calling is defined in the config, do I need a configuration section for each method?  
Can I put the code below in a base class and just use the `api` object like I would use an `HttpClient`?
How would I re-use the code below to make two or more consecutive calls to different methods on my api?

    var tokenAcquirerFactory = TokenAcquirerFactory.GetDefaultInstance();
    tokenAcquirerFactory.Services.AddDownstreamApi("MyApi",
    tokenAcquirerFactory.Configuration.GetSection("MyWebApi"));

    var sp = tokenAcquirerFactory.Build();
    var api = sp.GetRequiredService<IDownstreamApi>();

    var result = await api.GetForAppAsync<IEnumerable<TodoItem>>("MyApi");

Config:

    "MyWebApi": {
	"BaseUrl": "https://localhost:44372",
	"RelativePath": "/api/TodoList",
	"RequestAppToken": true,
	"Scopes": [ "api://42eb19ec-cf89-4a7c-8566-42b8d4920bdb/.default" ] // . E.g. 'api://<API_APPLICATION_ID>/.default'
    }

**Comment by jmprieur** [comment]
Not necessarily. you can also use overrides of `GetForAppSync` that provide a delegate ([Action<DownstreamApiOptions>,](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.abstractions.idownstreamapi.callapiasync?view=msal-model-dotnet-latest#microsoft-identity-abstractions-idownstreamapi-callapiasync(system-string-system-action((microsoft-identity-abstractions-downstreamapioptions))-system-security-claims-claimsprincipal-system-net-http-httpcontent-system-threading-cancellationtoken))) to change the configuration, or pass-in the configuration.
See https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.abstractions.idownstreamapi?view=msal-model-dotnet-latest
