### ISSUE TITLE
Reg: Creating GraphServiceClient with AuthenticationProvider

### ISSUE THREAD

**Issue by yChakradhar** [Azure-Samples/active-directory-dotnetcore-daemon-v2#39]
Hello Team,

We have developed windows based on ERP application, and Now we are integrating the one drive using the Graph SDK.  Following is the way how the app works.
1) Users can log in to the onedrive for the first time, then we are getting the access token and refresh tokens by calling the API endpoint.
2) Once we have the access tokens, we are preparing the GraphServiceClient by passing the access token we have using code file attached in the data.
Problem:
Using the latest version of Graph SDK there are changed in the IPublicClientApplication, and it seems we need to pass the AuthenticationProviders to the GraphServiceClient. While calling the ".Me.Request().GetAsync().Result" application is getting struck. I am a little confused here to create the authentication providers so please help to get out of the issue.
[AuthenticationHelper.txt](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/files/3683110/AuthenticationHelper.txt)
Thanks
Chakradhar

**Comment by TiagoBrenck** [comment]
Sorry, I didn't get your logic from the file you have attached. I got a few questions though:

   1. Where are you using your `_clientApp`?
   1. How are you acquiring token for Graph?
   1. Has it working before and then it stopped after you updated Graph SDK?

**Comment by yChakradhar** [comment]
Hi @TiagoBrenck,
The following are the answers to your questions.
A) We are not using the _ClientApp to get the tokens since we received Access Token and Refresh Tokens via using the Authentication EndPoint.
B) When the user first-time login into onedrive from our application, we are calling the endpoint "https://login.live.com/oauth20_authorize.srf?response_type=code" with client id and needed information getting the tokens and saving it in our local DB. So when a user called again we do use the appropriate tokens to connect one drive.
C) Previously we were using the older version of Graph SDK version, in that version we used public client application objects, now in the latest version of Graph SDK the methods have been deprecated. 

Please guide me to drive in the correct way if I am wrong.

Thank you
Chakradhar

**Comment by kalyankrishna1** [comment]
To keep up with the latest changes:

Download the following Nuget packages

- Microsoft.Graph
- Microsoft.Identity.Client
- Microsoft.Graph.Auth (check include pre-release)

then in the code, declare the following global variables
```

 	const string clientId = "Enter clientId from Portal";
        const string tenant = "<yourtenant>.onmicrosoft.com";
        const string redirectUri = "<redirect uri in portal starting with 'msal'>";

```

Then in your methods

```
>        string[] scopes = new string[] { "user.read", }; //Whatever you need
> 
>             IPublicClientApplication app = PublicClientApplicationBuilder.Create(clientId)
>                 .WithAuthority(new Uri($"https://login.microsoftonline.com/{tenant}"))
>                 .WithRedirectUri(redirectUri)
>                 .Build();
> 
>             // Initialize the Graph SDK authentication provider
>             InteractiveAuthenticationProvider authenticationProvider = new InteractiveAuthenticationProvider(app, scopes);
> 
>             GraphServiceClient graphServiceClient = new GraphServiceClient(authenticationProvider);
> 
> //Call the /me endpoint
> var me = await graphServiceClient.Me.Request().GetAsync();
>             Console.WriteLine($"Display Name from /me->{me.DisplayName}");
```

**Comment by yChakradhar** [comment]
Hi @kalyankrishna1 ,
We have tried to install the following NuGet package from the VS 2017. When we try to install it from NuGet package manager console using the following command getting the following error.

Install-Package Microsoft.Graph.Auth -Version 1.0.0-preview.1
Error Message:
Install-Package: Package 'Microsoft.Graph.Auth 1.0.0-preview.1' is not found in the following primary source(s): 'https://api.nuget.org/v3/index.json

We also tried to get by searching with the name but we dint find any. Please review and let us know your thoughts.

Regards,
Chakradhar

**Comment by kalyankrishna1** [comment]
[Microsoft.Graph.Auth](https://www.nuget.org/packages/Microsoft.Graph.Auth)

Use -IncludePrerelease in the install-package command as I've indicated earlier
