### ISSUE TITLE
can't get /me

### ISSUE THREAD

**Issue by quantrpeter** [Azure-Samples/active-directory-dotnetcore-daemon-v2#45]
Hi
    I can't call https://graph.microsoft.com/v1.0/me, why?

thanks
Peter
![image](https://user-images.githubusercontent.com/50471577/71177059-1296a700-22a6-11ea-9360-1c4c83a2c2c4.png)

**Comment by jmprieur** [comment]
@quantrpeter 
daemon applications get tokens on behalf of the application (that is with no user) to access data in the organization which is not specific to a user.

me is the information for a given user (which the daemon cannot get as there is no user)

**Comment by quantrpeter** [comment]
Thank you Mr Jmprieur
