### ISSUE TITLE
Project not working on .NET Core 3.1 and Microsoft.Identity.Web code seems outdated

### ISSUE THREAD

**Issue by MaximeMarck** [Azure-Samples/active-directory-dotnetcore-daemon-v2#47]
Hello Azure-Samples Team,

Thanks for all the code samples provided.
I have used the code in this project for an an on-premise daemon app that needs to call a web api hosted in Azure and protected by Azure AD.

As .net core 2.2 is not supported anymore I have updated my project to Asp.Net Core 3.1 and it was broken afterwards. After searching I found that the project under https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2 hosts a quite different (and probably more up-to-date) version of the Microsoft.Identity.Web project.

Could you please confirm that the version under https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/Microsoft.Identity.Web is the one that should be used for any .net core project needing Azure Ad integration and that it is compatible with .net core 3.1? 
Maybe this sample should also be updated for .NET Core 3.1?

I have also seen the request for providing Microsoft.Identity.Web as a nuget (https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/69) : I think it is a very good idea and would prevent issues like this one.

Many thanks

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Clone local project and upgrade web app https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/2-Call-OwnApi/TodoList-WebApi to asp.net core 3.1

### Any log messages given by the failure
Error at runtime

### Expected/desired behavior
N/A

### OS and Version?
Windows 10

### Versions
N/A

**Comment by TiagoBrenck** [comment]
@MaximeMarck I have created a PR updating the samples and library to core 3.1.

About the versions of Microsoft.Identity.Web, there is a task opened to sync them. But in the mean-time, I wouldn't say that the library on the web app tutorial samples is more or less up-to-date than this one, because we haven't sync them. So there is a chance of the web app tutorial library be missing code related to deamon applications only.

**Comment by therealburningman** [comment]
Although Closed. A very **clear** workaround OR how the solution was fixed is missing. @TiagoBrenck

**Comment by jmprieur** [comment]
@therealburningman 
Microsoft.Identity.Web is a preview package. Did you check the "preview" checkbox in the Visual Studio NuGet package management UI (or use -Preview if you use the command line) ?

**Comment by therealburningman** [comment]
> @therealburningman
> Microsoft.Identity.Web is a preview package. Did you check the "preview" checkbox in the Visual Studio NuGet package management UI (or use -Preview if you use the command line) ?

Makes sense. Thank you!
