### ISSUE TITLE
Related Python Document 

### ISSUE THREAD

**Issue by dsjijo** [Azure-Samples/active-directory-dotnetcore-daemon-v2#58]
I am unable to find the python version of this https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/blob/master/2-Call-OwnApi/README.md . If possible could you please comment the related python repository.

**Comment by jmprieur** [comment]
@dsjijo 
It's https://github.com/Azure-Samples/ms-identity-python-daemon

**Comment by dsjijo** [comment]
T

> @dsjijo
> It's https://github.com/Azure-Samples/ms-identity-python-daemon

Hi @jmprieur
Thanks for the reply . I have checked the same and found that its calling Graph API instead of Calling own API(python version). BTW I have found another repository doing the same [Link](https://github.com/Azure-Samples/ms-identity-python-webapi-azurefunctions/tree/master/Function/secureFlaskApp) . 

The token I was able to get through following this [link](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#first-case-access-token-request-with-a-shared-secret) and restructed my app like the   [secureFlaskApp](https://github.com/Azure-Samples/ms-identity-python-webapi-azurefunctions/tree/master/Function/secureFlaskApp). 

Thanks for the help.
