### ISSUE TITLE
Http GET returns 401 using the "2-Call-OwnApi" example

### ISSUE THREAD

**Issue by brassman2000** [Azure-Samples/active-directory-dotnetcore-daemon-v2#64]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>  An exercise to understand MSAL flows (coming from ADAL).

Started with existing AAD app registrations (one for the c# console and one for the Web API that was created using ASP.NET last year) and modified them as needed as per the provided PowerShell setup script.  Token is successfully obtained but Http GET returns 401 when calling the Web API.  

I can use ADAL with a C# console App and it works fine.  I can call the Web API (REST) via browser Url and interactive AAD login and it works fine.

### Any log messages given by the failure
> HttpResponseMessage response = await HttpClient.GetAsync(webApiUrl);
XXXXX to mask company specific values.
{StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  WWW-Authenticate: Bearer realm="XXXXXXX.azurewebsites.net" authorization_uri="https://login.microsoftonline.com/XXXXX/oauth2/authorize" resource_id="XXXXXXXX"
  X-Powered-By: ASP.NET
  Date: Thu, 07 May 2020 22:32:45 GMT
  Content-Length: 58
  Content-Type: text/html
}}

### Expected/desired behavior
>  Successful GET to Web API.

### OS and Version?
> Windows 10 1903.

### Versions
> VS2019

### Mention any other details that might be useful
Does Web API need to be refactored using NET Core for MSAL to work?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TiagoBrenck** [comment]
Hi @brassman2000 

In this sample, our web api is using the NuGet package `Microsoft.Identity.Web` to configure the jwt authentication, and unfortunately this package only works for .Net Core. However, if you dont want to refactor your api to .NET Core, it is completely fine, MSAL works on both frameworks.

My guess is that your api might be rejecting the token because of the audience (`aud` claim). Can you configure it to accept the audience as `api:\\<your-web-api-application-id>`?

**Comment by jmprieur** [comment]
@brassman2000 did you grant admin consent to your Web API?  (See step 6 of the README.md: https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/2-Call-OwnApi#register-the-client-app-daemon-console)

**Comment by brassman2000** [comment]
@TiagoBrenck , @jmprieur 

I confirmed consent was configured correctly.  
I was able to change the AAD app audience claim for the Web API App Service via the idenifierUri in the manifest
"identifierUris": [
		"api://myRESTWebAPI-api.azurewebsites.net"
	],
so that the token claim aud now displayed as "aud": "api://myRESTWebAPI-api.azurewebsites.net".

However, for my existing ASP.NET Web Api (NET framework 472), after changing web.config for the ida:audience 
from <add key="ida:Audience" value="**https**://myRESTWebAPI.azurewebsites.net" /> 
to <add key="ida:Audience" value="**api**://myRESTWebAPI-api.azurewebsites.net />

I am still getting the Http GET 401 error reported earlier.  I was using this exercise as preparation for the MS-600 certification and MSAL is one of the workloads - so unless there are any other ideas, we can close this case.   Appears I may need to refactor the Web API using NETCore.

Thanks!

**Comment by TiagoBrenck** [comment]
@brassman2000 it is easier if you get the access token sent by AAD (using fiddler for instance), and decode it (https://jwt.ms). Check the `aud` claim and see if it matches with the one configured in the web api. If they match, then we can discard this idea and look for something else that could be wrong.

**Comment by brassman2000** [comment]
@TiagoBrenck   Sorry if I was unclear in the last reply - that is what I was reporting back to you earlier:  the ASP.NET Web API web.config entry (add key="ida:Audience" value="api://myappreg.azurewebsites.net") now matches the aud claim in the access token (see below, edited for privacy) - but still get the Http 401.
{
  "typ": "JWT",
  "alg": "RS256",
  "x5t": "CtTuhMJmD5M7DLdzD2v2x3QKSRY",
  "kid": "CtTuhMJmD5M7DLdzD2v2x3QKSRY"
}.{
  "aud": "api://myappreg.azurewebsites.net",
  "iss": "https://sts.windows.net/GUID for Tenant/",
  "iat": 1589241026,
  "nbf": 1589241026,
  "exp": 1589244926,
  "aio": "42dgYFgpWbOr2yJwa/qK3z/2njqUDAA=",
  "appid": "GUID for App",
  "appidacr": "1",
  "idp": "https://sts.windows.net/GUID for Tenant/",
  "oid": "86c7ee17-b132-4936-8d36-f7b5679f8cbc",
  "roles": [
    "DaemonAppRole"
  ],
  "sub": "86c7ee17-b132-4936-8d36-f7b5679f8cbc",
  "tid": "GUID for Tenant",
  "uti": "0an9dQ1Zi0GSa22fWd-dAA",
  "ver": "1.0"
}.[Signature]

**Comment by TiagoBrenck** [comment]
Ok, so my second suggest would be the token issuer validation. You can quick check if this is what is being denied by removing the issuer validation:

```csharp
TokenValidationParameters = new TokenValidationParameters()
{
      ValidateIssuer = false
}
```

**Comment by jmprieur** [comment]
@brassman2000 :
1. Please don't disable issuer validation: you Web API would not be secure.

2. Can you please add to the **appconfig.json file** of your web api the following line:
 
`"Audience": "api://myappreg.azurewebsites.net"`

I see that you have an App ID URI that you have customized, and you need to tell the token validation about it.

your json flie should be something like

```JSon
{
	"AzureAd": {
		"Instance": "https://login.microsoftonline.com/",
		"ClientId": "<aguid>",
		"Domain": "<your domain>",
		"TenantId": "<your tenant ID>",
                "Audience": "api://myappreg.azurewebsites.net"
	},
       /// other lines
```

**Comment by TiagoBrenck** [comment]
@jmprieur his config is set to his custom api url.

Disabling the issuer was just a test to diagnose where is the API rejecting the token. Indeed, the intention is to keep `ValidateIssuer = true` to have a secure web api

**Comment by jmprieur** [comment]
Closing as this was answered (and is now documented)
