### ISSUE TITLE
 AADSTS7000215: Invalid client secret is provided. For 1st party app

### ISSUE THREAD

**Issue by AshleyYang25** [Azure-Samples/active-directory-dotnetcore-daemon-v2#66]
Hello team,
Thanks a lot for you excellent samples.
I want to use this sample that daemon app call MS Graph to test our 1st party app. But got invalid secret error.

How can I use my 1st party app to call MS graph?

Thanks a lot
Ashley

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
The 1st party app was registered in this [portal ](https://firstpartyportal.msidentity.com/), and I provisioned it to my test tenant by creating service principal manually, and assign credentials to that that service principal via [New-AzureADServicePrincipalPasswordCredential](https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadserviceprincipalpasswordcredential?view=azureadps-2.0), and got something like this:
![image](https://user-images.githubusercontent.com/22438762/83118243-b19ab700-a100-11ea-84a7-e3ec6085f894.png)
I used the 1st party app id and the value showed in the image to replace client id and secrets in appsettings.json.

### Any log messages given by the failure
>
When run the code, got invalid secrets error:
![image](https://user-images.githubusercontent.com/22438762/83118914-94b2b380-a101-11ea-985c-40f49b0594af.png)

### Expected/desired behavior
>
Use 1st party app to call MS graph successfully.
### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Win10
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@AshleyYang25 
for first party applications:
- you need to use certificates, not client secrets. See https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/1-Call-MSGraph#variation-daemon-application-using-client-credentials-with-certificates
- I believe that you need to acquire this certificate from SSL admin(not self create it).

**Comment by AshleyYang25** [comment]
> @AshleyYang25
> for first party applications:
> 
> * you need to use certificates, not client secrets. See https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/1-Call-MSGraph#variation-daemon-application-using-client-credentials-with-certificates
> * I believe that you need to acquire this certificate from SSL admin(not self create it).

Thank you so much for confirming this.
