### ISSUE TITLE
"The identity of the calling application could not be established." when "Tenant" is set to "organizations" (multi-tenant 3rd party app)

### ISSUE THREAD

**Issue by timefrozen19** [Azure-Samples/active-directory-dotnetcore-daemon-v2#68]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I followed the sample and was able to call Graph/users with specifying a specific AAD tenant in the "Tenant" configuration. I provisioned the 3rd party app to two tenants A and B, and be able to call Graph/users successfully when specifying tenant A or tenant B; however, when I configure "Tenant" to "organizations", I got the below error message.

### Any log messages given by the failure
>
```
Failed to call the Web Api: Unauthorized
Content: {
  "error": {
    "code": "Authorization_IdentityNotFound",
    "message": "The identity of the calling application could not be established.",
    "innerError": {
      "request-id": "069e1f34-ef65-4971-9436-644ad93d9543",
      "date": "2020-06-08T07:55:59"
    }
  }
}
```
### Expected/desired behavior
> Get all users from tenant A and tenant B since the third party app has been provisioned to both tenants.

### Mention any other details that might be useful
The app is registered as multi-tenant app. Is there any extra configuration needs to be set to call multiple tenant at once?
The individual successful call's token:
```
{
  "aud": "https://graph.microsoft.com",
  "iss": "https://sts.windows.net/5a04bd72-1be4-41a7-8b11-786d03a588da/",
  "iat": 1591599854,
  "nbf": 1591599854,
  "exp": 1591603754,
  "aio": "42dgYPgT0rcq3vdH3f7/v+5XG8gtAwA=",
  "app_displayname": "TodoList-webapi-daemon-v2",
  "appid": "0fd05c80-ecc3-499f-a151-801ff7587786",
  "appidacr": "1",
  "idp": "https://sts.windows.net/5a04bd72-1be4-41a7-8b11-786d03a588da/",
  "oid": "0a4fa8a7-4f39-4564-9f4c-30d421f9cad1",
  "roles": [
    "User.Read.All",
    "Organization.Read.All"
  ],
  "sub": "0a4fa8a7-4f39-4564-9f4c-30d421f9cad1",
  "tenant_region_scope": "NA",
  "tid": "5a04bd72-1be4-41a7-8b11-786d03a588da",
  "uti": "tTN8PcA6zESxYnwy6WDAAA",
  "ver": "1.0",
  "xms_tcdt": 1587097936
}
```
The failed call's token:
```
{
  "aud": "https://graph.microsoft.com",
  "iss": "https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/",
  "iat": 1591602138,
  "nbf": 1591602138,
  "exp": 1591688838,
  "aio": "42dgYODgNK8s/8Z7tjJ5k5JLy0IHAA==",
  "app_displayname": "TodoList-webapi-daemon-v2",
  "appid": "0fd05c80-ecc3-499f-a151-801ff7587786",
  "appidacr": "1",
  "idp": "https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/",
  "tenant_region_scope": "WW",
  "tid": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "uti": "na-E2oVbOUmuZDVWAV0iAA",
  "ver": "1.0",
  "xms_tcdt": 1289241547
}
```

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
Multi-tenant cross tenant applications can be declared as such at the app registration, but in the code you would have to provide a tenanted authority;

In particular MIcrosoft.Graph would not be able to merge information from different tenants.

To enable the scenario you need to have a list of the tenants domain or tenant ID and iterate to call the MIcrosoft Graph from your daemon app.

If you need a more dynamic scenario, like doing that for all the tenants accessible by a given user, you could have a look at the following sample which enumerates the tenants accessible by a given user: (this is done here: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/3-WebApp-multi-APIs/Services/ARM/ArmOperationsService.cs, and called from https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/307231246b4d8400294c5ce20c94b1fadf5e7870/3-WebApp-multi-APIs/Controllers/HomeController.cs#L56-L69

HTH
