### ISSUE TITLE
Usage of Todolist service without "roles" claim

### ISSUE THREAD

**Issue by M-Yankov** [Azure-Samples/active-directory-dotnetcore-daemon-v2#69]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> In TodoList controller add another method, but without Policy or roles   

I am following the instructions in **2-Call-OwnApi**. If I want to register another client app in Azure, but do not grant any Application permissions (roles). The token that will be issued will not have roles claim - which is OK. When the client tries to access an endpoint (method) from TodoList service, that doesn't require roles or policy, the response is "Neither scope or roles claim was found in the bearer token.".

```c#
// note that there is no [Roles or Policy] required.
[HttpGet("Categories")]
public IActionResult CategoriesForTodos()
{
    // Cannot access the endpoint if none of "scp", "scope", "role", "role" claims present in the token.
    // If all are missing - error.
    
    // related categories to that application in Azure.
    return Ok(new[] { "category1", "category2" });
}

```

### Any log messages given by the failure
> System.UnauthorizedAccessException: Neither scope or roles claim was found in the bearer token.
   at Microsoft.Identity.Web.WebApiAuthenticationBuilderExtensions.<>c__DisplayClass1_1.<<AddProtectedWebApi>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### Expected/desired behavior
> Access the endpoint - 200 OK

### OS and Version?
> Windows 10.

### Versions
> VS2019

### Mention any other details that might be useful
Is it necessary all tokens to have "roles" claim ? How to add a method that doesn't require role or polices.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TiagoBrenck** [comment]
It is Microsoft.Identity.Web who is validating this for you. We added this validation to ensure that the Web API only accepts access tokens from tenants where it has been consented and provisioned.

**Comment by M-Yankov** [comment]
Yeah, I was little confused with managed permissions (but there are for another flow). I am migrating from ADAL to MSAL. Currently delegated permissions are used between service and client app. I understand now that "application permissions" should be used instead, because my flow is to get token (clientId, clientSecret, scope- AppUriId/.default) and then to use that token (Authentication bearer {token}) to access the service. In this case Todolist service API. And that service API should always require a defined role from the token - for example "TodolistApiAccess". I think to use this attribute on Controller [Authorize(Policy = "ApiAccess")] or [Authorize(Roles = "TodolistApiAccess")].

Thanks for the comment.

**Comment by TiagoBrenck** [comment]
*Application permissions* are used when you need a communication between 2 servers (no users nor interactions are involved at all).
