### ISSUE TITLE
Mismatch between the code and the documentation code snippets for the 2-Call-OwnApi solution

### ISSUE THREAD

**Issue by coxantohi** [Azure-Samples/active-directory-dotnetcore-daemon-v2#73]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>NA

### Any log messages given by the failure
>NA

### Expected/desired behavior
>NA

### OS and Version?
>NA

### Versions
>NA

### Mention any other details that might be useful
The section [TodoList Web API Code](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/2-Call-OwnApi#todolist-web-api-code) references code not being part of the project.
The `Startup.cs` file does not have calls made to `AddAzureADBearer` for example.
The documentation does not explain `services.AddProtectedWebApi(Configuration)`.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jennyf19** [comment]
@coxantohi looks like the documentation has been updated. is there something more specific you are looking for?

**Comment by jennyf19** [comment]
i think this has been updated. closing for now.
