### ISSUE TITLE
HTTP Error 500.34 - ANCM Mixed Hosting Models Not Supported

### ISSUE THREAD

**Issue by draper** [Azure-Samples/active-directory-dotnetcore-daemon-v2#75]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Trying to access the API from the Daemon results in a 500.34 error.

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> 10

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TiagoBrenck** [comment]
Hi @draper could you please give us more details about this issue? Also, steps on how we can reproduce it on our end?

Thanks

**Comment by draper** [comment]
Fixed this myself... This error occurred with using IIS express as the launch profile.  I switched to WebAPI and it worked fine.

**Comment by TiagoBrenck** [comment]
Thanks for sharing the solution.
