### ISSUE TITLE
2-Call-OwnApi wiki documents no longer match the code 

### ISSUE THREAD

**Issue by syendev** [Azure-Samples/active-directory-dotnetcore-daemon-v2#82]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> read directions, `About the code` section, `TodoList Web API Code` section refers to pre July 1st commit, as contents listed are no longer present in Startup.cs.

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TiagoBrenck** [comment]
Thanks for the check. I ve opened a PR updating the documentation.
