### ISSUE TITLE
Code doesn't match documentation also not explained 

### ISSUE THREAD

**Issue by LiorZivi** [Azure-Samples/active-directory-dotnetcore-daemon-v2#83]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TiagoBrenck** [comment]
@LiorZivi I ve updated the README to fix #82 .

For your code not explained complain, please provide us more details. What code is not explained? What line in the code or README are you struggling?

Looking forward to hear more details from you.
Thanks
