### ISSUE TITLE
Possible to call Azure FHIR API using MSAL authentication process

### ISSUE THREAD

**Issue by RahulKate** [Azure-Samples/active-directory-dotnetcore-daemon-v2#89]
I am using MSAL daemon server authentication mechanism to call FHIR API using example specified in below link,
https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2

I tried with sample application, able to retrieve access token using MSAL library but its giving **forbidden error** while calling FHIR API from daemon process, Is it possible to access FHIR API using daemon application?

![image](https://user-images.githubusercontent.com/13742253/91970714-aecde480-ed35-11ea-9458-4a6bac337dbf.png)

Its mentioned in MSAL sample application that we need application permission in order to access API, let me know if it is possible to provide application permission for FHIR API from app registration, currently application permission for Azure Healthcare API is disabled and not able to add as shown in below image,

![image](https://user-images.githubusercontent.com/13742253/91970409-42eb7c00-ed35-11ea-94f3-15ab483551e0.png)

**Comment by jmprieur** [comment]
@RahulKate I'm a bit surprized that the scope user_impersonation be used for application permissions (which have no user by definition).

@SaeedAkhter-MSFT : do you have a contact info in Azure Healthcare API?

**Comment by hansenms** [comment]
user_impersonation is not used. This question has been cross posted on the fhir-server-samples repo and @ginalee-dotcom from the FHIR API team will handle it. I think you can close it here. It is not related to the MSAL library or this sample.

**Comment by RahulKate** [comment]
Closing issue as this will be addressed in below thread,

https://github.com/microsoft/fhir-server-samples/issues/90
