### ISSUE TITLE
Lower case 'bearer' vs. 'Bearer' raises exception

### ISSUE THREAD

**Issue by sepple-ms** [Azure-Samples/active-directory-dotnetcore-daemon-v2#90]
Below should be changed to be 'Bearer' and not 'bearer' as per https://tools.ietf.org/html/rfc6750:

https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/blob/89d84515a99e2c8c87ba5617bfa5d953545e13a6/1-Call-MSGraph/daemon-console/ProtectedApiCallHelper.cs#L67

and 

https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/blob/89d84515a99e2c8c87ba5617bfa5d953545e13a6/2-Call-OwnApi/daemon-console/ProtectedApiCallHelper.cs#L68

Depending on the target you are calling, an exception such as below may be raised:
{"error":{"code":"InvalidHeaderValue","message":"Authorization header token does not start with 'Bearer ' scheme."}}

**Comment by jennyf19** [comment]
fixed. thank you @sepple-ms
