### ISSUE TITLE
Insufficient privileges to complete the operation.

### ISSUE THREAD

**Issue by Epiccode887** [Azure-Samples/active-directory-dotnetcore-daemon-v2#97]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Once you run the app creation script, we get the below mentioned error. Do we need to assign any specific roles to the user?
>

### Any log messages given by the failure
Creating the AAD application (XXX)
**Error occurred while executing NewApplication
Code: Authorization_RequestDenied
Message: Insufficient privileges to complete the operation.**
>

### Expected/desired behavior
>

### OS and Version?
> Windows Server 2012 R2

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@Epiccode887: did you do the manual step (which is to admin consent to the application permission)? See Step 6 of https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/1-Call-MSGraph#register-the-client-app-daemon-console.

If yes, it can take a few seconds to be effective.

**Comment by Epiccode887** [comment]
@jmprieur, No, we haven't done the manual step. But since we are using the PS script to register an application, providing Admin Consent would be at a later stage right? i.e. once the application gets registered?

The script seems to be failing even before creating an app. Do we need to assign any specific roles to the user registering an app?

**Comment by jmprieur** [comment]
@Epiccode887 : yes, you should have the rights to create applications in the directory. I don't think you'd need more.

**Comment by Epiccode887** [comment]
Thanks @jmprieur. On the User settings page, we had App registrations set to No, hence we were unable to register an app using non-admin user.

**Comment by jmprieur** [comment]
Good to read you self troubleshooted the issue @Epiccode887 
Proposing to close it.
